### PR TITLE
Added the solution to CSES problem two sets

### PR DESCRIPTION
**Pull request by Suyyashaa**
Added the solution to CSES problem two sets

### CODE REVIEW

**Review by aksh1407 — CHANGES_REQUESTED** [review]
Kindly make required changes in this [file](https://github.com/1gne0u5/Learning-Resources/tree/master/Competitive%20Programming/Solutions/CSES/Introductory%20Problems) mentioning the problem name and the link to your solution with the programming language mentioned as well. Thanks.

**Comment by Suyyashaa** [comment]
I have made the required changes.

**Review by aksh1407 — APPROVED** [review]
Awesome!

**Comment by Suyyashaa** [comment]
Thanks a lot! 😄

**Pull request merged**
