### PR TITLE
Added Backend development file, and more to web development resources

### PR DESCRIPTION
**Pull request by Bhavishya2912**
Added some more resources to Web development folder.
And created a new folder for Backend development, with books, learning path, and various backend language learning resources.

### CODE REVIEW

**Review by blank-27 — APPROVED** [review]
lgtm

**Comment by Sylvester-dev** [comment]
@Bhavishya2912 there are some conflict files here (Web Development/Resources/README.md) so please check and resolve those conflicts.

**Review by Bhavishya2912 — COMMENTED** [review]
Conflicting files reviewed.

**Review by aksh1407 — CHANGES_REQUESTED** [review]
Kindly create a sub-folder inside the Web Development directory, for Back-End Development and store your resources their instead of having a separate directory for it. Thanks!

**Review by Sylvester-dev — APPROVED** [review]

**Comment by Bhavishya2912** [comment]
> Kindly create a sub-folder inside the Web Development directory, for Back-End Development and store your resources their instead of having a separate directory for it. Thanks!

#79 changes made in new pull request

**Pull request closed without merging**
