### PR TITLE
Added Some Books for learning ML and AI

### PR DESCRIPTION
**Pull request by prikshitsetia**
Added 8 great books for learning ML, AI, and Data Analysis

### CODE REVIEW

**Comment by prikshitsetia** [comment]
Also added a todo application on ejs, css, express and mongodb

**Review by aksh1407 — CHANGES_REQUESTED** [review]
Kindly create a separate folder inside [**Resources**](https://github.com/1gne0u5/Learning-Resources/tree/master/Machine%20Learning/Resources) folder of Machine Learning named **Books** and store the books there.

Change the file names to **Book Title**[*Author*]

**Comment by archana-17** [comment]
Kindly provide the pdf for the book "A_guide_to_expert_systems".

**Comment by prikshitsetia** [comment]
I have made the required changes.

**Review by archana-17 — APPROVED** [review]

**Pull request merged**
