### PR TITLE
added numberSpiral.cpp

### PR DESCRIPTION
**Pull request by siddhantmohanty2001**

### CODE REVIEW

**Review by aksh1407 — CHANGES_REQUESTED** [review]
Kindly update the [readme](https://github.com/1gne0u5/Learning-Resources/blob/master/Competitive%20Programming/Solutions/CSES/Introductory%20Problems/readme.md) file with a link to your solution.

**Review by siddhantmohanty2001 — COMMENTED** [review]
updated readme.md

**Comment by siddhantmohanty2001** [comment]
Necessary changes have been made

**Review by aksh1407 — APPROVED** [review]
Looks good! 👍🏼

**Pull request merged**
