### PR TITLE
Added a solution to the codechef problem Chef and reversing

### PR DESCRIPTION
**Pull request by Suyyashaa**

### CODE REVIEW

**Comment by AyushiPanth** [comment]
Kindly mention the link of the problem or add the problem statement in the comments, in the code itself

**Comment by Suyyashaa** [comment]
File has been changed.

**Review by aksh1407 — CHANGES_REQUESTED** [review]
I'm sorry we were not looking for this. Would you like to rather add a Data Structure or an Algorithm, in the [DSALGO](https://github.com/1gne0u5/Learning-Resources/tree/master/Competitive%20Programming/DSALGO) directory?

**Comment by Suyyashaa** [comment]
.

**Pull request closed without merging**
